export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../assets/images/categories-20241009T220844Z-001/categories/icons8-pizza-96.png"),
  },
  {
    id: 2,
    name: "Burger",
    image: require("../assets/images/categories-20241009T220844Z-001/categories/icons8-pizza-96.png"),
  },
  {
    id: 3,
    name: "Italian",
    image: require("../assets/images/categories-20241009T220844Z-001/categories/icons8-pizza-96.png"),
  },
  {
    id: 4,
    name: "Chinese",
    image: require("../assets/images/categories-20241009T220844Z-001/categories/icons8-pizza-96.png"),
  },
  {
    id: 5,
    name: "Noodles",
    image: require("../assets/images/categories-20241009T220844Z-001/categories/icons8-pizza-96.png"),
  },
  {
    id: 6,
    name: "Sweets",
    image: require("../assets/images/categories-20241009T220844Z-001/categories/icons8-pizza-96.png"),
  },
];

export const featured = {
  id: 1,
  title: "Hot and Spicy",
  description: "soft and tender fried chicken",
  restaurants: [
    {
      id: 1,
      name: "Papa Johns",
      image: require("../assets/images/restaurants/papaJohns.jpg"),
      description: "Hot and Spicy Pizzas",
      lng: 37.78825,
      lat: -122.4324,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/dishes/pizza.jpeg"),
        },
        {
          id: 2,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/dishes/pizza.jpeg"),
        },
        {
          id: 3,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/dishes/pizza.jpeg"),
        },
      ],
    },
    {
      id: 2,
      name: "Papa Johns",
      image: require("../assets/images/restaurants/papaJohns.jpg"),
      description: "Hot and Spicy Pizzas",
      lng: 37.78825,
      lat: -122.4324,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/dishes/pizza.jpeg"),
        },
        {
          id: 2,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/dishes/pizza.jpeg"),
        },
        {
          id: 3,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/dishes/pizza.jpeg"),
        },
      ],
    },
    {
      id: 3,
      name: "Papa Johns",
      image: require("../assets/images/restaurants/papaJohns.jpg"),
      description: "Hot and Spicy Pizzas",
      lng: 37.78825,
      lat: -122.4324,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/dishes/pizza.jpeg"),
        },
        {
          id: 2,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/dishes/pizza.jpeg"),
        },
        {
          id: 3,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/dishes/pizza.jpeg"),
        },
      ],
    },
    {
      id: 4,
      name: "Papa Johns",
      image: require("../assets/images/restaurants/papaJohns.jpg"),
      description: "Hot and Spicy Pizzas",
      lng: 37.78825,
      lat: -122.4324,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/dishes/pizza.jpeg"),
        },
        {
          id: 2,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/dishes/pizza.jpeg"),
        },
        {
          id: 3,
          name: "Pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../assets/images/dishes/pizza.jpeg"),
        },
      ],
    },
  ],
};
