export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../assets/images/categories-20/categories/icons8-pizza-96.png"),
  },
  {
    id: 2,
    name: "Burger",
    image: require("../assets/images/categories-20/categories/icons8-hamburger-96.png"),
  },
  {
    id: 3,
    name: "Drinks",
    image: require("../assets/images/categories-20/categories/icons8-tropical-drink-96.png"),
  },
  {
    id: 4,
    name: "Chinese",
    image: require("../assets/images/categories-20/categories/icons8-takeout-box-96.png"),
  },
  {
    id: 5,
    name: "Noodles",
    image: require("../assets/images/categories-20/categories/icons8-spaghetti-96.png"),
  },
  {
    id: 6,
    name: "Sea Food",
    image: require("../assets/images/categories-20/categories/icons8-tropical-fish-96.png"),
  },
  {
    id: 7,
    name: "Sweets",
    image: require("../assets/images/categories-20/categories/icons8-cupcake-emoji-96.png"),
  },
];

export const featured = [
  {
    id: 1,
    title: "HOT & SPICY",
    description: "soft and tender fried chicken",
    restaurants: [
      {
        id: 1,
        name: "Papa Johns",
        image: require("../assets/images/restaurants/papaJohns.jpg"),
        description: "Hot and Spicy Pizzas",
        lng: 37.78825,
        lat: -122.4324,
        address: "123 main street",
        stars: 4,
        reviews: "4.2k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Burger",
            description: "Beef Burger",
            price: 12,
            image: require("../assets/images/dishes/burger.jpeg"),
          },
          {
            id: 2,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 18,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
          {
            id: 3,
            name: "Fried Chicken ",
            description: "Fried Chicken with sos",
            price: 16,
            image: require("../assets/images/dishes/fingerchicken.jpeg"),
          },
          {
            id: 4,
            name: "Hot Chicken ",
            description: "Chicken with hot sos",
            price: 15,
            image: require("../assets/images/dishes/chicken.jpeg"),
          },
        ],
      },
      {
        id: 2,
        name: "KFC",
        image: require("../assets/images/restaurants/kfc.webp"),
        description: "Hot and Spicy Pizzas",
        lng: 37.78825,
        lat: -122.4324,
        address: "777 flower street",
        stars: 3,
        reviews: "3.2k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "KFC Special Menu",
            description: "mix chicken and burger",
            price: 21,
            image: require("../assets/images/dishes/kfcMenuu.jpg"),
          },
          {
            id: 2,
            name: "Chicken Menu",
            description: "Chicken Burger, French Fries and Drink",
            price: 12,
            image: require("../assets/images/dishes/chickenMenu.webp"),
          },
          {
            id: 3,
            name: "Hot Wings Special",
            description: "Fried Wings ",
            price: 14,
            image: require("../assets/images/dishes/HOTwings.webp"),
          },
          {
            id: 4,
            name: "Chicken ",
            description: "Chicken with hot sos",
            price: 15,
            image: require("../assets/images/dishes/chicken.jpeg"),
          },
        ],
      },
      {
        id: 3,
        name: "Chicken World",
        image: require("../assets/images/restaurants/download (7).jpeg"),
        description: "Hot and Spicy Pizzas",
        lng: 37.78825,
        lat: -122.4324,
        address: "888 done street",
        stars: 4,
        reviews: "4.1k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Fried Chicken ",
            description: "Fried Chicken with sos",
            price: 16,
            image: require("../assets/images/dishes/fingerchicken.jpeg"),
          },
          {
            id: 2,
            name: "Hot Chicken ",
            description: "Chicken with hot sos",
            price: 15,
            image: require("../assets/images/dishes/chicken.jpeg"),
          },
          {
            id: 3,
            name: "Chicken Menu",
            description: "Chicken Burger, French Fries and Drink",
            price: 12,
            image: require("../assets/images/dishes/chickenMenu.webp"),
          },
        ],
      },
      {
        id: 4,
        name: "Fast Food House",
        image: require("../assets/images/restaurants/disadvantages-of-fast-food (1).webp"),
        description: "Hot and Spicy Pizzas",
        lng: 37.78825,
        lat: -122.4324,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
          {
            id: 2,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
          {
            id: 3,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "FRIED CHICKEN",
    description: "soft and tender fried chicken",
    restaurants: [
      {
        id: 4,
        name: "Fast Food House",
        image: require("../assets/images/restaurants/disadvantages-of-fast-food (1).webp"),
        description: "Hot and Spicy Pizzas",
        lng: 37.78825,
        lat: -122.4324,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
          {
            id: 2,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
          {
            id: 3,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
        ],
      },

      {
        id: 3,
        name: "Hot Chicken",
        image: require("../assets/images/restaurants/download (7).jpeg"),
        description: "Hot and Spicy Pizzas",
        lng: 37.78825,
        lat: -122.4324,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
          {
            id: 2,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
          {
            id: 3,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
        ],
      },
      {
        id: 2,
        name: "KFC",
        image: require("../assets/images/restaurants/kfc.webp"),
        description: "Hot and Spicy Pizzas",
        lng: 37.78825,
        lat: -122.4324,
        address: "777 flower street",
        stars: 3,
        reviews: "3.2k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "KFC Special Menu",
            description: "mix chicken and burger",
            price: 21,
            image: require("../assets/images/dishes/kfcMenuu.jpg"),
          },
          {
            id: 2,
            name: "Chicken Menu",
            description: "Chicken Burger, French Fries and Drink",
            price: 12,
            image: require("../assets/images/dishes/chickenMenu.webp"),
          },
          {
            id: 3,
            name: "Hot Wings Special",
            description: "Fried Wings ",
            price: 14,
            image: require("../assets/images/dishes/HOTwings.webp"),
          },
          {
            id: 4,
            name: "Chicken ",
            description: "Chicken with hot sos",
            price: 15,
            image: require("../assets/images/dishes/chicken.jpeg"),
          },
        ],
      },

      {
        id: 1,
        name: "Papa Johns",
        image: require("../assets/images/restaurants/papaJohns.jpg"),
        description: "Hot and Spicy Pizzas",
        lng: 37.78825,
        lat: -122.4324,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "burger",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
          {
            id: 2,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
          {
            id: 3,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: "CHINESE",
    description: "soft and tender fried chicken",
    restaurants: [
      {
        id: 4,
        name: "Sushi Astaca",
        image: require("../assets/images/restaurants/sushi.jpg"),
        description: "Hot and Spicy Pizzas",
        lng: 37.78825,
        lat: -122.4324,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Kawaii Chinese & Sushi",
            description: "Sushi Rolls",
            price: 11,
            image: require("../assets/images/dishes/KawaiiChinese&Sushi.jpg"),
          },
          {
            id: 2,
            name: "Noodle",
            description: "Noodle",
            price: 14,
            image: require("../assets/images/dishes/noodle.jpeg"),
          },
          {
            id: 3,
            name: "Best Sushi  ",
            description: "Sushi with Special Sos",
            price: 15,
            image: require("../assets/images/dishes/bestSushi.webp"),
          },
          {
            id: 4,
            name: "Rice ",
            description: "Rice with Special Sos",
            price: 9,
            image: require("../assets/images/dishes/riceWhite.jpeg"),
          },
        ],
      },
      {
        id: 1,
        name: "Uncles Place",
        image: require("../assets/images/restaurants/rawImage (1).jpg"),
        description: "Hot and Spicy Pizzas",
        lng: 37.78825,
        lat: -122.4324,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Rice With Vegetables",
            description: "cheezy garlic pizza",
            price: 11,
            image: require("../assets/images/dishes/vegetableRice.jpeg"),
          },
          {
            id: 2,
            name: "Noodle",
            description: "Noodle",
            price: 14,
            image: require("../assets/images/dishes/noodle.jpeg"),
          },
          {
            id: 3,
            name: "Rice ",
            description: "Rice with Special Sos",
            price: 10,
            image: require("../assets/images/dishes/riceWhite.jpeg"),
          },
        ],
      },
      {
        id: 2,
        name: "Chinese Dishes House",
        image: require("../assets/images/restaurants/Chinese+Foods.jpg"),
        description: "Hot and Spicy Pizzas",
        lng: 37.78825,
        lat: -122.4324,
        address: "434 second street",
        stars: 4,
        reviews: "4.1k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "burger",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
          {
            id: 2,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
          {
            id: 3,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
        ],
      },

      {
        id: 3,
        name: "NoodleMOO",
        image: require("../assets/images/restaurants/noodleRESTRNT2.webp"),
        description: "Hot and Spicy Pizzas",
        lng: 37.78825,
        lat: -122.4324,
        address: "582 firs street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
          {
            id: 2,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
          {
            id: 3,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
        ],
      },
      {
        id: 4,
        name: "Fast Food House",
        image: require("../assets/images/restaurants/disadvantages-of-fast-food (1).webp"),
        description: "Hot and Spicy Pizzas",
        lng: 37.78825,
        lat: -122.4324,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
          {
            id: 2,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
          {
            id: 3,
            name: "Pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/dishes/pizza.jpeg"),
          },
        ],
      },
    ],
  },
];
